### ISSUE TITLE
Compiling application Issues on master 

### ISSUE THREAD

**Issue by Camcdonou** [thielepaul/photoprism-mobile#117]
I am trying to compile the project myself and I am getting an issue where 

_The name 'Album' isn't a type so it can't be used as a type argument.
Try correcting the name to an existing type, or defining a type named 'Album'.dartnon_type_as_type_argument_

and

_The method 'close' isn't defined for the type 'MyDatabase'.
Try correcting the name to the name of an existing method, or defining a method named 'close'.dartundefined_method_

and 

_PhotoprismModel model
The argument type 'dynamic' can't be assigned to the parameter type 'String'.dartargument_type_not_assignable_

(there is more but you get the point)

Am I doing something wrong while trying to compile the code?

Flutter Doctor:

[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19041.928], locale en-US)
    • Flutter version 2.0.5 at C:\Users\*\AppData\Local\flutter
    • Framework revision adc687823a (3 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\*\AppData\Local\Android
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = C:\Users\*\AppData\Local\Android
    • ANDROID_SDK_ROOT = C:\Users\*\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Community Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2020.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2020.2.3
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code, 64-bit edition (version 1.55.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (1 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)

• No issues found!

I've tried using:
flutter clean
flutter pub cache repair 
flutter pub get

Thank you

**Comment by Mortein** [comment]
Could you be missing the Flutter `build_runner` step?

See https://github.com/photoprism/photoprism-mobile/blob/master/CONTRIBUTING.md

**Comment by Camcdonou** [comment]
> Could you be missing the Flutter `build_runner` step?
> 
> See https://github.com/photoprism/photoprism-mobile/blob/master/CONTRIBUTING.md

That did indeed fix it. Thank you very much. I didn't see that.
