### ISSUE TITLE
Can I help with app?

### ISSUE THREAD

**Issue by vaibhavarora14** [thielepaul/photoprism-mobile#120]
I know progressive web apps
React native apps

I just need some KT and initial walkthrough to save time

**Comment by gomme600** [comment]
I would also be interested in helping but unfortunately I have never done app design before.

**Comment by ITCMD** [comment]
> I know progressive web apps
> React native apps
> 
> I just need some KT and initial walkthrough to save time

It seems like this repo is fairly abandoned. The app in the first place is community driven, so anyone can feel free to fork their own version. However, getting a walkthough might be tough.
