### ISSUE TITLE
No ARM/ARM64 image for experimental image thielepaul/photoprism:db-api

### ISSUE THREAD

**Issue by gomme600** [thielepaul/photoprism-mobile#123]
I was unable to use the experimental image "thielepaul/photoprism:db-api" on my raspberry pi 4. This means that until the official merge request is accepted the photoprism mobile app is unusable.

**Comment by nolimitek** [comment]
Yes please make it useable for arm

**Comment by thielepaul** [comment]
I have built an image, however I have no arm64 cpu so I can not test it:
`thielepaul/photoprism:db-api-arm64`

**Comment by gomme600** [comment]
The container seems to have started up ok for me! Will have to try uploading photos when I get home. Thanks for the ready to use image!

**Comment by gomme600** [comment]
Uploading a video manually worked via mobile data so I am going th close this. Will check autoupload later but I don't see any reason why it wouldn't work. Thanks again @thielepaul for this!

**Comment by thielepaul** [comment]
as photoprism now supports the docker buildx multiplatform build, the arm64 image no longer has a seperate tag but can also be downloaded by the main tag `thielepaul/photoprism:db-api`

**Comment by gomme600** [comment]
> as photoprism now supports the docker buildx multiplatform build, the arm64 image no longer has a seperate tag but can also be downloaded by the main tag `thielepaul/photoprism:db-api`

Just tried and it didn't work unfortunately. I am getting this : standard_init_linux.go:219: exec user process caused: exec format error

**Comment by thielepaul** [comment]
> Just tried and it didn't work unfortunately. I am getting this : standard_init_linux.go:219: exec user process caused: exec format error

Can you try if `--platform linux/arm64` or `platform: linux/arm64` (docker-compose) works for you?

**Comment by Helinos** [comment]
I'm not super well versed with docker so excuse my lack of knowledge.
But whenever I try to pull this image on my Raspberry Pi 3, I get the following error:
`no matching manifest for unknown in the manifest list entries`

Any help would be appreciated.
