### ISSUE TITLE
The "PhotoPrism" authentication flag is not saved

### ISSUE THREAD

**Issue by xxxserxxx** [thielepaul/photoprism-mobile#135]
The toggle for the "PhotoPrism" authentication method (on/off) is not persisted between app restarts. The credentials themselves *are* saved, but the toggle must be re-enabled between restarts. This prevents PhotoPrism Mobile from syncing in the background.

- PhotoPrism Mobile: Development CI build (991746f)
- Android: 12; Samsung One UI 4.0
- PhotoPrism server: docker.io/thielepaul/photoprism:db-api (09aebf7f69ab)

### To replicate

1. Start PhotoPrism mobile
2. Go to Settings
3. Go to Authentication
4. Enable "PhotoPrism" and enter credentials
5. Save the settings
5. Back out to the main (gallery) screen
6. Exit app

Cause the app to stop. This issue presents itself if Android puts the app to sleep on its own; however, to force the behavior, either:

7. Go to the running app list overview (square home button, on my phone)
8. Swipe up on PhotoPrism

**or**

7. Go to the Android system settings and the Apps section
8. Find PhotoPrism and select it
9. Click "Force Stop"

After Android's stopped PhotoPrism,

10. Start PhotoPrism Mobile again
11. Go to Settings
12. Go to Authentication
13. *All authentication methods will be disabled*

At this point, if PhotoPrism Authentication is re-enabled, the credentials are there and it works fine for the session. If the app stops for any reason, the Authentication flag will be disabled again.

**Comment by thielepaul** [comment]
Please try if it is working with the latest version

**Comment by xxxserxxx** [comment]
Perfect! Thank you for the quick fix!
