### ISSUE TITLE
thumbnails are showing but fullscreen pics won't

### ISSUE THREAD

**Issue by NablaMetal** [thielepaul/photoprism-mobile#139]
Hi,
Thanks for that incredible piece of work. This app is very nice and runs nicely but I was wondering if I'm the only one who can't have pictures going fullscreen when taping a thumbnail (screen goes fullscreen grey, like it is loading but nothing happens).
I use a Andorid up-to-date Huawei P30 for that matters.

**Comment by 1Herby1** [comment]
Hey,
I have the same problem.

**Comment by Suncadgeek** [comment]
fixed in 2d3788e
thank you very much ! works great :)

**Comment by NablaMetal** [comment]
thank you
