### ISSUE TITLE
Subject search not working correctly

### ISSUE THREAD

**Issue by xleisj** [thielepaul/photoprism-mobile#140]
I have a lot of photos which contain face tags in the file which i already added in Lightroom classic. When i index these photos the names of the people in the photo are correctly added to the subject metadata field of the image inside photoprism. But the problem is, that if i search for a subject that is in the photo no photos are showing up. I tried the following search queries (below the query you can find the logs of the server):

**query 1:**
`subject:"Isabelle Zbinden"`

**Logs query 1:**
```
time="2022-04-19T11:40:27Z" level=debug msg="photos: found 0 results for public:true dist:20 year:0 month:0 subject:\"Isabelle Zbinden\" quality:3 count:60 order:newest merged:true [4.127326ms]"
time="2022-04-19T11:40:27Z" level=debug msg="http: GET /api/v1/photos?count=60&offset=0&merged=true&country=&camera=0&lens=0&label=&year=0&month=0&color=&order=newest&q=subject:%22Isabelle+Zbinden%22&public=true&quality=3 (200) [4.668572ms]"
```

**query 2:**
`subjects:"Isabelle Zbinden"`

**Logs query 2:**
```
time="2022-04-19T11:43:49Z" level=debug msg="photos: found 0 results for public:true dist:20 year:0 month:0 subjects:\"Isabelle Zbinden\" quality:3 count:60 order:newest merged:true [3.221747ms]"
time="2022-04-19T11:43:49Z" level=debug msg="http: GET /api/v1/photos?count=60&offset=0&merged=true&country=&camera=0&lens=0&label=&year=0&month=0&color=&order=newest&q=subjects:%22Isabelle+Zbinden%22&public=true&quality=3 (200) [3.624868ms]"
```

**query 3:**
`person:"Isabelle Zbinden"`

**Logs query 3:**
```
time="2022-04-19T11:44:18Z" level=debug msg="photos: found 0 results for public:true dist:20 year:0 month:0 subject:\"Isabelle Zbinden\" quality:3 count:60 order:newest merged:true [4.350162ms]"
time="2022-04-19T11:44:18Z" level=debug msg="http: GET /api/v1/photos?count=60&offset=0&merged=true&country=&camera=0&lens=0&label=&year=0&month=0&color=&order=newest&q=person:%22Isabelle+Zbinden%22&public=true&quality=3 (200) [4.892169ms]"
```

**query 4:**
`people:"Isabelle Zbinden"`

**Logs query 4:**
```
time="2022-04-19T11:44:43Z" level=debug msg="photos: found 0 results for public:true dist:20 year:0 month:0 subjects:\"Isabelle Zbinden\" quality:3 count:60 order:newest merged:true [4.338983ms]"
time="2022-04-19T11:44:43Z" level=debug msg="http: GET /api/v1/photos?count=60&offset=0&merged=true&country=&camera=0&lens=0&label=&year=0&month=0&color=&order=newest&q=people:%22Isabelle+Zbinden%22&public=true&quality=3 (200) [4.874767ms]"
```

I am able to add a name to a face in photoprism under the "people" section. If I then search for this person the photo appears. But it seems as if i am not able to search specifically for the contents of the subject field in the photoprism search. Is there a way to search for photos that contain a specific text/name in the subject field?

**Comment by graciousgrey** [comment]
The subject search filter is only looking for matches in people(=subjects) see https://docs.photoprism.app/user-guide/organize/search/#search-filter-overview

I admit it's a bit confusing.

The subject field from the details tab is included in the full text search, so you can search for `Isabelle Zbinden`

There is no dedicated search filter for the subject from the details tab for performance reasons (will be improved later).

Note that the search is implemented in (https://github.com/photoprism/photoprism)

**Comment by xleisj** [comment]
Thank you very much for the fast answer. It is now clear to me how it works. It would be very great to have a search filter for the subject field from the details tab. The problem with the full search is the following in my case:

The subjects i added in the file with lightroom are added to the subject field in the following form "Isabelle Zbinden, Jonas Leiser". This is ok and if a search filter would exist it would allow me to search for this specific person. However the subject names are also imported into the keywords section of the image in the following form "isabelle, zbinden, jonas, leiser". So if i search in the full text search for `Isabelle Zbinden` it would also find photos containing another Isabelle (Isabelle Müller for exmaple). If i search for `keywords:jonas&leiser` it would also show photos which have the persons "Jonas Fischer" and "Fritz Leiser" in them. So i have no real way of searching for specific persons.

I understood that there is currently no way for doing that, but i just wanted to clarify why this would be a very appreciated feature.
