### ISSUE TITLE
Compatible Photoprism version 

### ISSUE THREAD

**Issue by z4ch523** [thielepaul/photoprism-mobile#147]
I cannot find the photoprism version I have to use in order to test this App. Could you please add this information to the readme?

Thanks

**Comment by thielepaul** [comment]
https://github.com/thielepaul/photoprism-mobile#currently-incompatible-with-photoprism-warning

> If you want to use the latest version of the app until this is merged, you can either build the photoprism backend with the patches from [source](https://github.com/thielepaul/photoprism/tree/db-api) or use the docker image thielepaul/photoprism:db-api.
