### ISSUE TITLE
Selected Photos Issue

### ISSUE THREAD

**Issue by ollimaz** [thielepaul/photoprism-mobile#57]
Hello,

i found a bug! 

### Current Behaviour:
When Selecting Photos in "Photos" then changing tabs to "Albums" or "Settings" and then going back to the tab "Photos" the Topbar is still in Selection Mode but no Photos are selected anymore

Some Screenshots:
![Screenshot_20200425-134354](https://user-images.githubusercontent.com/62832771/80279181-23e03c00-86fc-11ea-9dcc-983e8a936486.jpg)
![Screenshot_20200425-134403](https://user-images.githubusercontent.com/62832771/80279186-28a4f000-86fc-11ea-9764-85b6c9eb0680.jpg)
![Screenshot_20200425-134409](https://user-images.githubusercontent.com/62832771/80279187-2b9fe080-86fc-11ea-95bd-e202f6bee21d.jpg)

_________________________
Using UpToDate-Verion of Andorid 10 on a Samsung Phone

### Expected Behaviour: 
Either having the Photos still selected when changing tabs
or 
all selected pictures gets unselected and the Topbar changes back to normal view.

**Comment by thielepaul** [comment]
Good catch! I am currently busy with other stuff, if anyone wants to fix this feel free to open a pull request :)

**Comment by thielepaul** [comment]
should be fixed via f3eac47125a1485b8d632cb4689304e3ad747395
