### ISSUE TITLE
Share multiple Photos

### ISSUE THREAD

**Issue by ollimaz** [thielepaul/photoprism-mobile#58]
Hii,

It would be really nice if you could add the feature to share Multiple Photos. Currently the Share Button is only available on the Picture View. What about to show it on the Topbar when you have selected some Photos?

**Comment by thielepaul** [comment]
you can check out the new version, sharing of multiple photos was added in 541f538ecef50c7fadaea348c918f8afa2120c03

**Comment by ollimaz** [comment]
Works perfectly fine. Thx
