### ISSUE TITLE
Help with using authentication

### ISSUE THREAD

**Issue by nicoolaro** [thielepaul/photoprism-mobile#66]
Hi ,

I followed the guide on setting Photoprism as a docker.
My credentials are the same as in the guide : admin & ***
I added IP address in the app and used Basic HTTP 
every time i try to upload or create album it says "failed", no pictures are shown

Do i need to do anything else?

**Comment by thielepaul** [comment]
I am not sure, if I understand your setup: do you use the the authentication provided by PhotoPrism or HTTP BASIC authentication (https://en.wikipedia.org/wiki/Basic_access_authentication) or both?

The app supports these two authentication schemes, if you only use one of them you should only enable the one you use in the settings.

**Comment by nicoolaro** [comment]
> I am not sure, if I understand your setup: do you use the the authentication provided by PhotoPrism or HTTP BASIC authentication (https://en.wikipedia.org/wiki/Basic_access_authentication) or both?
> 
> The app supports these two authentication schemes, if you only use one of them you should only enable the one you use in the settings.

I solved it by enabling both, that's the only way it worked.

I use PhotoPrism

**Comment by nicoolaro** [comment]
solved
