### ISSUE TITLE
[iOS] Videos not displaying in videos tab

### ISSUE THREAD

**Issue by jbenitosantoni** [thielepaul/photoprism-mobile#91]
Videos are not showing up in the videos menu tab of the iOS app.

It just shows a blank screen, I attach screenshot

![IMG_7C3D95DC1328-1](https://user-images.githubusercontent.com/54249303/106332580-5fa9c280-6287-11eb-8efe-c764379f375d.jpeg)

**Comment by thielepaul** [comment]
this will be fixed when https://github.com/photoprism/photoprism-mobile/pull/96 is merged
