### ISSUE TITLE
Don't show images/videos marked private by default

### ISSUE THREAD

**Issue by mrrsm** [thielepaul/photoprism-mobile#98]
I'd like to see an option on the photos/videos pages to toggle showing private images inline with the items already marked as public.

**Comment by thielepaul** [comment]
would you prefer if the filter is persistent over app restarts or should it reset? Or should there both be a non-persistent filter on the photos-page and a persistent filter (which can be configured in the settings page)?

**Comment by mrrsm** [comment]
I personally would like it as a persistent setting.  In my PR I had it as an option in the drop down on the photos/videos/etc pages where the upload button was.  My thinking on that is that would become the place where all of the filter options could be set in the future and in theory could be separated for all of the main categories (photos, video, albums).

These thoughts are a bit out of scope but how I could see it working based on the current design:
The current mobile design boils it down into only a few main categories so in general I would think that having persistent filters or even quick filter options to get to other views which are present in the web would be nice.

**Comment by thielepaul** [comment]
This is how it currently looks, I think I will add a "set as default" button next to the apply button.

![Screenshot_20210211-201943](https://user-images.githubusercontent.com/2041078/107687296-9aa7ef00-6ca6-11eb-9cc4-a313fa83f455.png)

**Comment by mrrsm** [comment]
That looks great!

If that is something in the main app settings wouldn't the expected use case automatically be setting it as default as it is a setting?

If this is a popup filter from the photos page I can see it working exactly as you said as I always want the ability to make my temporary changes sticky.

**Comment by thielepaul** [comment]
yes it is a popup from the photos page
